-- Crear tabla mesas si no existe
create table if not exists public.mesas (
  id bigint generated by default as identity primary key,
  nombre text not null
);

-- Crear tabla productos si no existe
create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  precio integer not null,
  categoria text
);

-- Crear tabla pedidos si no existe
create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  mesa text not null,
  estado text not null default 'pendiente',
  total integer default 0
);

-- Crear tabla detalle si no existe
create table if not exists public.detalle (
  id bigint generated by default as identity primary key,
  pedido_id bigint references public.pedidos(id) on delete cascade,
  producto text not null,
  cantidad integer not null default 1
);

-- Habilitar RLS opcionalmente (pero mantenerlo desactivado para simplicidad)
alter table public.mesas disable row level security;
alter table public.productos disable row level security;
alter table public.pedidos disable row level security;
alter table public.detalle disable row level security;